import {
  GiPirateCannon,
  GiEagleEmblem,
  GiElvenCastle,
  GiChicken,
  GiDevilMask,
  GiHawkEmblem,
  GiSeagull,
  GiLion,
  GiBatwingEmblem,
  GiBee,
  GiIndianPalace,
  GiSwordsEmblem,
  GiFox,
  GiSoccerBall,
} from 'react-icons/gi'

export const categories = [
  { name: 'Arsenal', icon: <GiPirateCannon /> },
  { name: 'Man City', icon: <GiEagleEmblem /> },
  { name: 'Newcastle', icon: <GiElvenCastle /> },
  { name: 'Tottenham', icon: <GiChicken /> },
  { name: 'Man United', icon: <GiDevilMask /> },
  { name: 'Liverpool', icon: <GiHawkEmblem /> },
  { name: 'Brighton', icon: <GiSeagull /> },
  { name: 'Chelsea', icon: <GiLion /> },
  { name: 'Fulham', icon: <GiBatwingEmblem /> },
  { name: 'Brentford', icon: <GiBee /> },
  { name: 'Crystal palace', icon: <GiIndianPalace /> },
  { name: 'Aston Villa', icon: <GiSwordsEmblem /> },
  { name: 'Leicester City', icon: <GiFox /> },
  { name: 'Bournemouth', icon: <GiSoccerBall /> },
]
